language: emacs-lisp
env:
  # Run all basic unit tests on both Emacs versions
  - TRAVIS_BUILD=unit EMACS=emacs24
  - TRAVIS_BUILD=unit EMACS=emacs-snapshot
  # Run integration tests on Emacs snapshot only.  That should be sufficient to
  # catch most bugs
  - TRAVIS_BUILD=integration EMACS=emacs-snapshot
before_install:
  - make -f travis.mk before_install
  - source /etc/profile
  - export PATH="${GOPATH}/bin:${HOME}/.local/bin:$PATH"
install:
  - make -f travis.mk install
script:
  - make -f travis.mk script
matrix:
  # Fast fail if any job fails.  We don't need to run all integration tests, if
  # the unit tests fail already.
  fast_finish: true
